[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-surround'
 
[[plugins]]
repo = 'vim-airline/vim-airline'
